# Form implementation generated from reading ui file 'D:\KTLT PROJECT FINAL\ProjectKTLT\ui\BookingOrderRoomWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1222, 865)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1211, 811))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/image/BACKGROUND.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(720, 100, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(720, 160, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.dateTimeEditCheckIn = QtWidgets.QDateTimeEdit(parent=self.centralwidget)
        self.dateTimeEditCheckIn.setGeometry(QtCore.QRect(950, 110, 191, 31))
        self.dateTimeEditCheckIn.setStyleSheet("QDateTimeEdit {\n"
"    background-color: white;  /* Màu nền trắng */\n"
"    color: #2c3e50; /* Màu chữ xanh đậm */\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"}\n"
"QDateTimeEdit::drop-down {\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"QDateTimeEdit::up-button, QDateTimeEdit::down-button {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    background-color: #3498db;\n"
"}\n"
"QDateTimeEdit::up-button:hover, QDateTimeEdit::down-button:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"")
        self.dateTimeEditCheckIn.setObjectName("dateTimeEditCheckIn")
        self.dateTimeEditCheckOut = QtWidgets.QDateTimeEdit(parent=self.centralwidget)
        self.dateTimeEditCheckOut.setGeometry(QtCore.QRect(950, 170, 191, 31))
        self.dateTimeEditCheckOut.setStyleSheet("QDateTimeEdit {\n"
"    background-color: white;  /* Màu nền trắng */\n"
"    color: #2c3e50; /* Màu chữ xanh đậm */\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"}\n"
"QDateTimeEdit::drop-down {\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"QDateTimeEdit::up-button, QDateTimeEdit::down-button {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    background-color: #3498db;\n"
"}\n"
"QDateTimeEdit::up-button:hover, QDateTimeEdit::down-button:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"")
        self.dateTimeEditCheckOut.setObjectName("dateTimeEditCheckOut")
        self.checkBoxCatharis = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxCatharis.setGeometry(QtCore.QRect(20, 220, 301, 421))
        self.checkBoxCatharis.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/Catharsis.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.checkBoxCatharis.setIcon(icon)
        self.checkBoxCatharis.setIconSize(QtCore.QSize(400, 400))
        self.checkBoxCatharis.setObjectName("checkBoxCatharis")
        self.checkBoxOasis = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxOasis.setGeometry(QtCore.QRect(320, 220, 301, 421))
        self.checkBoxOasis.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/Oasis.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.checkBoxOasis.setIcon(icon1)
        self.checkBoxOasis.setIconSize(QtCore.QSize(400, 400))
        self.checkBoxOasis.setObjectName("checkBoxOasis")
        self.checkBoxGenii = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxGenii.setGeometry(QtCore.QRect(610, 220, 301, 421))
        self.checkBoxGenii.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/Genii.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.checkBoxGenii.setIcon(icon2)
        self.checkBoxGenii.setIconSize(QtCore.QSize(400, 400))
        self.checkBoxGenii.setObjectName("checkBoxGenii")
        self.checkBoxMutiny = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxMutiny.setGeometry(QtCore.QRect(900, 220, 301, 421))
        self.checkBoxMutiny.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/Mutiny.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.checkBoxMutiny.setIcon(icon3)
        self.checkBoxMutiny.setIconSize(QtCore.QSize(400, 400))
        self.checkBoxMutiny.setObjectName("checkBoxMutiny")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 640, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(350, 640, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(640, 640, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(930, 640, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 311, 81))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;  /* Màu chữ */\n"
"}")
        self.pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/TITLE.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(300, 200))
        self.pushButton.setObjectName("pushButton")
        self.pushButtonBangGia = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBangGia.setGeometry(QtCore.QRect(940, 30, 111, 41))
        self.pushButtonBangGia.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;  /* Màu chữ */\n"
"}")
        self.pushButtonBangGia.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/Bảng giá.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBangGia.setIcon(icon5)
        self.pushButtonBangGia.setIconSize(QtCore.QSize(100, 150))
        self.pushButtonBangGia.setObjectName("pushButtonBangGia")
        self.pushButtonLienHe = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLienHe.setGeometry(QtCore.QRect(1050, 30, 101, 41))
        self.pushButtonLienHe.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;  /* Màu chữ */\n"
"}")
        self.pushButtonLienHe.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/Liên hệ.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLienHe.setIcon(icon6)
        self.pushButtonLienHe.setIconSize(QtCore.QSize(85, 90))
        self.pushButtonLienHe.setObjectName("pushButtonLienHe")
        self.pushButtonDatPhong = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDatPhong.setGeometry(QtCore.QRect(810, 30, 131, 41))
        self.pushButtonDatPhong.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;  /* Màu chữ */\n"
"}")
        self.pushButtonDatPhong.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/Đặt phòng_.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonDatPhong.setIcon(icon7)
        self.pushButtonDatPhong.setIconSize(QtCore.QSize(120, 150))
        self.pushButtonDatPhong.setObjectName("pushButtonDatPhong")
        self.pushButtonPhongChoi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPhongChoi.setGeometry(QtCore.QRect(670, 30, 131, 41))
        self.pushButtonPhongChoi.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;  /* Màu chữ */\n"
"}")
        self.pushButtonPhongChoi.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/Phòng chơi.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPhongChoi.setIcon(icon8)
        self.pushButtonPhongChoi.setIconSize(QtCore.QSize(130, 150))
        self.pushButtonPhongChoi.setObjectName("pushButtonPhongChoi")
        self.pushButtonTrangChu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonTrangChu.setGeometry(QtCore.QRect(550, 30, 111, 41))
        self.pushButtonTrangChu.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;  /* Màu chữ */\n"
"}")
        self.pushButtonTrangChu.setText("")
        self.pushButtonTrangChu.setIcon(icon5)
        self.pushButtonTrangChu.setIconSize(QtCore.QSize(100, 150))
        self.pushButtonTrangChu.setObjectName("pushButtonTrangChu")
        self.pushButtonBaGach = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBaGach.setGeometry(QtCore.QRect(1150, 30, 61, 41))
        self.pushButtonBaGach.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;  /* Màu chữ */\n"
"}")
        self.pushButtonBaGach.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/3 GẠCH.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBaGach.setIcon(icon9)
        self.pushButtonBaGach.setIconSize(QtCore.QSize(40, 50))
        self.pushButtonBaGach.setObjectName("pushButtonBaGach")
        self.lineEditCatharis = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditCatharis.setGeometry(QtCore.QRect(170, 650, 111, 31))
        self.lineEditCatharis.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 15px;  /* Điều chỉnh giá trị để bo góc nhiều hơn */\n"
"    padding: 5px;\n"
"}")
        self.lineEditCatharis.setObjectName("lineEditCatharis")
        self.lineEditOasis = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditOasis.setGeometry(QtCore.QRect(470, 650, 111, 31))
        self.lineEditOasis.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 15px;  /* Điều chỉnh giá trị để bo góc nhiều hơn */\n"
"    padding: 5px;\n"
"}")
        self.lineEditOasis.setObjectName("lineEditOasis")
        self.lineEditGenii = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditGenii.setGeometry(QtCore.QRect(760, 650, 111, 31))
        self.lineEditGenii.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 15px;  /* Điều chỉnh giá trị để bo góc nhiều hơn */\n"
"    padding: 5px;\n"
"}")
        self.lineEditGenii.setObjectName("lineEditGenii")
        self.lineEditMutiny = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditMutiny.setGeometry(QtCore.QRect(1050, 650, 111, 31))
        self.lineEditMutiny.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 15px;  /* Điều chỉnh giá trị để bo góc nhiều hơn */\n"
"    padding: 5px;\n"
"}")
        self.lineEditMutiny.setObjectName("lineEditMutiny")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 130, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #3498db; /* Màu nền xanh */\n"
"    color: white; /* Màu chữ */\n"
"    border-radius: 20px; /* Bo góc */\n"
"    padding: 10px;\n"
"    font-size: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #2980b9; /* Màu khi hover */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1c598a; /* Màu khi bấm */\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEditMutiny_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditMutiny_2.setGeometry(QtCore.QRect(140, 190, 351, 31))
        self.lineEditMutiny_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #3498db;\n"
"    border-radius: 15px;  /* Điều chỉnh giá trị để bo góc nhiều hơn */\n"
"    padding: 5px;\n"
"}")
        self.lineEditMutiny_2.setObjectName("lineEditMutiny_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1222, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Check-in Time:"))
        self.label_7.setText(_translate("MainWindow", "Check-out Time:"))
        self.label_8.setText(_translate("MainWindow", "Số lượng:"))
        self.label_9.setText(_translate("MainWindow", "Số lượng:"))
        self.label_10.setText(_translate("MainWindow", "Số lượng:"))
        self.label_11.setText(_translate("MainWindow", "Số lượng:"))
        self.pushButton_2.setText(_translate("MainWindow", "Nhân viên tư vấn tâm lý"))
