# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\ProjectKTLT\ui\ChoosePsyConsultant.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget


class Ui_MainWindow(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1060, 650)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1041, 591))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/image/BG Home Window.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 210, 52, 15))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.tableWidgetPysConsultant = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetPysConsultant.setGeometry(QtCore.QRect(60, 130, 491, 361))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(10)
        self.tableWidgetPysConsultant.setFont(font)
        self.tableWidgetPysConsultant.setStyleSheet("QTableWidget {\n"
"    background-color: rgba(255, 255, 255, 100); /* Màu nền bảng với độ trong suốt */\n"
"    color: white; /* Màu chữ */\n"
"    font-size: 10pt; /* Kích thước font chữ */\n"
"    font-family: \"#9Slide03 Oswald Bold\";\n"
"}")
        self.tableWidgetPysConsultant.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.tableWidgetPysConsultant.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.tableWidgetPysConsultant.setObjectName("tableWidgetPysConsultant")
        self.tableWidgetPysConsultant.setColumnCount(5)
        self.tableWidgetPysConsultant.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidgetPysConsultant.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(225, 225, 225, 100))
        self.tableWidgetPysConsultant.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetPysConsultant.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetPysConsultant.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetPysConsultant.setHorizontalHeaderItem(4, item)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(580, 120, 401, 361))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 11pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";")
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 61, 21))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEditPsyID = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPsyID.setEnabled(False)
        self.lineEditPsyID.setGeometry(QtCore.QRect(100, 40, 281, 21))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(10)
        self.lineEditPsyID.setFont(font)
        self.lineEditPsyID.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 0.5px solid white;\n"
"border-radius: 7px;\n"
"font-size: 10pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"")
        self.lineEditPsyID.setObjectName("lineEditPsyID")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 80, 61, 21))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEditName = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditName.setEnabled(False)
        self.lineEditName.setGeometry(QtCore.QRect(100, 80, 281, 21))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(10)
        self.lineEditName.setFont(font)
        self.lineEditName.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 0.5px solid white;\n"
"border-radius: 7px;\n"
"font-size: 10pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";")
        self.lineEditName.setObjectName("lineEditName")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditEmail.setEnabled(False)
        self.lineEditEmail.setGeometry(QtCore.QRect(100, 120, 281, 21))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(10)
        self.lineEditEmail.setFont(font)
        self.lineEditEmail.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 0.5px solid white;\n"
"border-radius: 7px;\n"
"font-size: 10pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.lineEditPhone = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPhone.setEnabled(False)
        self.lineEditPhone.setGeometry(QtCore.QRect(100, 160, 281, 21))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(10)
        self.lineEditPhone.setFont(font)
        self.lineEditPhone.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 0.5px solid white;\n"
"border-radius: 7px;\n"
"font-size: 10pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"")
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 120, 61, 21))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(30, 200, 61, 21))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEditWorkshift = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditWorkshift.setEnabled(False)
        self.lineEditWorkshift.setGeometry(QtCore.QRect(110, 240, 271, 21))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(10)
        self.lineEditWorkshift.setFont(font)
        self.lineEditWorkshift.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 0.5px solid white;\n"
"border-radius: 7px;\n"
"font-size: 10pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"")
        self.lineEditWorkshift.setObjectName("lineEditWorkshift")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(30, 280, 131, 21))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEditYearofExperience = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditYearofExperience.setEnabled(False)
        self.lineEditYearofExperience.setGeometry(QtCore.QRect(180, 280, 201, 21))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(10)
        self.lineEditYearofExperience.setFont(font)
        self.lineEditYearofExperience.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 0.5px solid white;\n"
"border-radius: 7px;\n"
"font-size: 10pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"")
        self.lineEditYearofExperience.setObjectName("lineEditYearofExperience")
        self.lineEditAddress = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditAddress.setEnabled(False)
        self.lineEditAddress.setGeometry(QtCore.QRect(100, 200, 281, 21))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(10)
        self.lineEditAddress.setFont(font)
        self.lineEditAddress.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 0.5px solid white;\n"
"border-radius: 7px;\n"
"font-size: 10pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";")
        self.lineEditAddress.setObjectName("lineEditAddress")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(30, 320, 121, 21))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEditCustomerRate = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditCustomerRate.setEnabled(False)
        self.lineEditCustomerRate.setGeometry(QtCore.QRect(180, 320, 201, 21))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(10)
        self.lineEditCustomerRate.setFont(font)
        self.lineEditCustomerRate.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 0.5px solid white;\n"
"border-radius: 7px;\n"
"font-size: 10pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";")
        self.lineEditCustomerRate.setObjectName("lineEditCustomerRate")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(30, 240, 71, 21))
        font = QtGui.QFont()
        font.setFamily("#9Slide03 Oswald Bold")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pushButtonChoosePsyConsultant = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonChoosePsyConsultant.setGeometry(QtCore.QRect(290, 510, 371, 71))
        self.pushButtonChoosePsyConsultant.setAutoFillBackground(False)
        self.pushButtonChoosePsyConsultant.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"")
        self.pushButtonChoosePsyConsultant.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Choose PsyConsultant.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonChoosePsyConsultant.setIcon(icon)
        self.pushButtonChoosePsyConsultant.setIconSize(QtCore.QSize(200, 200))
        self.pushButtonChoosePsyConsultant.setObjectName("pushButtonChoosePsyConsultant")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(530, 510, 201, 71))
        self.pushButtonExit.setStyleSheet("background-color: transparent;\n"
"border: none;")
        self.pushButtonExit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon1)
        self.pushButtonExit.setIconSize(QtCore.QSize(90, 90))
        self.pushButtonExit.setObjectName("pushButtonExit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def __init__(self):
        super().__init__()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Panacea - Choose Psychology Consultant"))
        item = self.tableWidgetPysConsultant.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PsyID"))
        item = self.tableWidgetPysConsultant.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidgetPysConsultant.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Workshift"))
        item = self.tableWidgetPysConsultant.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Year of experience"))
        item = self.tableWidgetPysConsultant.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Customer Rate"))
        self.groupBox.setTitle(_translate("MainWindow", "Details:"))
        self.label_3.setText(_translate("MainWindow", "ID:"))
        self.label_4.setText(_translate("MainWindow", "Name: "))
        self.label_5.setText(_translate("MainWindow", "Email:"))
        self.label_6.setText(_translate("MainWindow", "Phone:"))
        self.label_7.setText(_translate("MainWindow", "Address:"))
        self.label_8.setText(_translate("MainWindow", "Year of experience:"))
        self.label_9.setText(_translate("MainWindow", "Customer Rate:"))
        self.label_10.setText(_translate("MainWindow", "Workshift:"))
