# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\ProjectKTLT\ui\DirectPaymentWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 854)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, -5, 1231, 811))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/image/DIRECT PAYMENT.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEditCashier = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditCashier.setGeometry(QtCore.QRect(320, 340, 611, 41))
        self.lineEditCashier.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Màu nền trắng */\n"
"    color: #2c3e50; /* Màu chữ xanh đậm */\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px;\n"
"    font-size: 25px;\n"
"    font-weight:bold;\n"
"}")
        self.lineEditCashier.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditCashier.setObjectName("lineEditCashier")
        self.lineEditAmountPaid = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditAmountPaid.setGeometry(QtCore.QRect(330, 540, 601, 41))
        self.lineEditAmountPaid.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Màu nền trắng */\n"
"    color: #2c3e50; /* Màu chữ xanh đậm */\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px;\n"
"    font-size: 25px;\n"
"    font-weight:bold;\n"
"}")
        self.lineEditAmountPaid.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditAmountPaid.setObjectName("lineEditAmountPaid")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(970, 160, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonExit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/x.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon)
        self.pushButtonExit.setIconSize(QtCore.QSize(70, 100))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.pushButtonMail = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMail.setGeometry(QtCore.QRect(1130, 510, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonMail.setFont(font)
        self.pushButtonMail.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonMail.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/MAIL.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonMail.setIcon(icon1)
        self.pushButtonMail.setIconSize(QtCore.QSize(70, 100))
        self.pushButtonMail.setObjectName("pushButtonMail")
        self.pushButtonPhone = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPhone.setGeometry(QtCore.QRect(1120, 600, 101, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonPhone.setFont(font)
        self.pushButtonPhone.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonPhone.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/PHONE.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPhone.setIcon(icon2)
        self.pushButtonPhone.setIconSize(QtCore.QSize(100, 70))
        self.pushButtonPhone.setObjectName("pushButtonPhone")
        self.pushButtonFacebook = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonFacebook.setGeometry(QtCore.QRect(1130, 700, 81, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonFacebook.setFont(font)
        self.pushButtonFacebook.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonFacebook.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/facebook-logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonFacebook.setIcon(icon3)
        self.pushButtonFacebook.setIconSize(QtCore.QSize(70, 80))
        self.pushButtonFacebook.setObjectName("pushButtonFacebook")
        self.pushButtonConfirmPayment = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonConfirmPayment.setGeometry(QtCore.QRect(440, 650, 391, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonConfirmPayment.setFont(font)
        self.pushButtonConfirmPayment.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonConfirmPayment.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Confirm Payment.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonConfirmPayment.setIcon(icon4)
        self.pushButtonConfirmPayment.setIconSize(QtCore.QSize(350, 300))
        self.pushButtonConfirmPayment.setObjectName("pushButtonConfirmPayment")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1220, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
