# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\ProjectKTLT\ui\FeedBackWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1222, 860)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEditContent = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEditContent.setGeometry(QtCore.QRect(430, 250, 491, 131))
        self.textEditContent.setStyleSheet("QTextEdit {\n"
"    background-color: white;\n"
"    color: black;\n"
"    font-size: 16px;\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 8px;\n"
"}")
        self.textEditContent.setObjectName("textEditContent")
        self.dateEditDateRate = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEditDateRate.setGeometry(QtCore.QRect(430, 560, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.dateEditDateRate.setFont(font)
        self.dateEditDateRate.setStyleSheet("QDateTimeEdit {\n"
"    background-color: white;  /* Màu nền trắng */\n"
"    color: #2c3e50; /* Màu chữ xanh đậm */\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px;\n"
"    font-size: 30px;\n"
"}\n"
"QDateTimeEdit::drop-down {\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"QDateTimeEdit::up-button, QDateTimeEdit::down-button {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    background-color: #3498db;\n"
"}\n"
"QDateTimeEdit::up-button:hover, QDateTimeEdit::down-button:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"Family Font: \"Time New Roman\"")
        self.dateEditDateRate.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dateEditDateRate.setObjectName("dateEditDateRate")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditUserName.setGeometry(QtCore.QRect(430, 410, 491, 41))
        self.lineEditUserName.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Màu nền trắng */\n"
"    color: #2c3e50; /* Màu chữ xanh đậm */\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px;\n"
"    font-size: 25px;\n"
"    font-weight:bold;\n"
"}")
        self.lineEditUserName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.lineEditIDRoom = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditIDRoom.setGeometry(QtCore.QRect(430, 480, 491, 41))
        self.lineEditIDRoom.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Màu nền trắng */\n"
"    color: #2c3e50; /* Màu chữ xanh đậm */\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px;\n"
"    font-size: 25px;\n"
"    font-weight:bold;\n"
"}")
        self.lineEditIDRoom.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditIDRoom.setObjectName("lineEditIDRoom")
        self.pushButtonPhone = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPhone.setGeometry(QtCore.QRect(1100, 580, 101, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonPhone.setFont(font)
        self.pushButtonPhone.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonPhone.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/PHONE.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPhone.setIcon(icon)
        self.pushButtonPhone.setIconSize(QtCore.QSize(100, 70))
        self.pushButtonPhone.setObjectName("pushButtonPhone")
        self.lineEditRate = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditRate.setGeometry(QtCore.QRect(430, 640, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditRate.setFont(font)
        self.lineEditRate.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Màu nền trắng */\n"
"    color: #2c3e50; /* Màu chữ xanh đậm */\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px;\n"
"    font-size: 25px;\n"
"    font-weight:bold, italic;\n"
"}")
        self.lineEditRate.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditRate.setObjectName("lineEditRate")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(870, 630, 51, 51))
        self.label_4.setStyleSheet("QLineEdit {\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    border: none; /* Không viền */\n"
"    color: white; /* Màu chữ */\n"
"    font-size: 16px;\n"
"    padding: 5px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-bottom: 2px solid #3498db; /* Viền dưới khi focus */\n"
"}\n"
"")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/star.png"))
        self.label_4.setObjectName("label_4")
        self.pushButtonFacebook = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonFacebook.setGeometry(QtCore.QRect(1110, 690, 81, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonFacebook.setFont(font)
        self.pushButtonFacebook.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonFacebook.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/facebook-logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonFacebook.setIcon(icon1)
        self.pushButtonFacebook.setIconSize(QtCore.QSize(70, 80))
        self.pushButtonFacebook.setObjectName("pushButtonFacebook")
        self.pushButtonMail = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMail.setGeometry(QtCore.QRect(1110, 480, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonMail.setFont(font)
        self.pushButtonMail.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonMail.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/MAIL.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonMail.setIcon(icon2)
        self.pushButtonMail.setIconSize(QtCore.QSize(70, 100))
        self.pushButtonMail.setObjectName("pushButtonMail")
        self.pushButtonSendFeedback = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSendFeedback.setGeometry(QtCore.QRect(460, 720, 391, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonSendFeedback.setFont(font)
        self.pushButtonSendFeedback.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonSendFeedback.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/SENDFEEDBACK.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSendFeedback.setIcon(icon3)
        self.pushButtonSendFeedback.setIconSize(QtCore.QSize(350, 300))
        self.pushButtonSendFeedback.setObjectName("pushButtonSendFeedback")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1231, 811))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/image/FEEDBACK.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButtonContact = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonContact.setGeometry(QtCore.QRect(1020, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonContact.setFont(font)
        self.pushButtonContact.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonContact.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/CONTACT.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonContact.setIcon(icon4)
        self.pushButtonContact.setIconSize(QtCore.QSize(95, 100))
        self.pushButtonContact.setObjectName("pushButtonContact")
        self.pushButtonHome = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonHome.setGeometry(QtCore.QRect(590, 40, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonHome.setFont(font)
        self.pushButtonHome.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonHome.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/HOME.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonHome.setIcon(icon5)
        self.pushButtonHome.setIconSize(QtCore.QSize(65, 100))
        self.pushButtonHome.setObjectName("pushButtonHome")
        self.pushButtonOrder = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonOrder.setGeometry(QtCore.QRect(830, 40, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonOrder.setFont(font)
        self.pushButtonOrder.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonOrder.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/ORDER.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonOrder.setIcon(icon6)
        self.pushButtonOrder.setIconSize(QtCore.QSize(75, 100))
        self.pushButtonOrder.setObjectName("pushButtonOrder")
        self.pushButtonPlayRoom = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPlayRoom.setGeometry(QtCore.QRect(680, 40, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonPlayRoom.setFont(font)
        self.pushButtonPlayRoom.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonPlayRoom.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/PLAY ROOM.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPlayRoom.setIcon(icon7)
        self.pushButtonPlayRoom.setIconSize(QtCore.QSize(120, 100))
        self.pushButtonPlayRoom.setObjectName("pushButtonPlayRoom")
        self.pushButtonPrice = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPrice.setGeometry(QtCore.QRect(930, 40, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonPrice.setFont(font)
        self.pushButtonPrice.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonPrice.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/PRICE.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPrice.setIcon(icon8)
        self.pushButtonPrice.setIconSize(QtCore.QSize(65, 100))
        self.pushButtonPrice.setObjectName("pushButtonPrice")
        self.pushButtonMore = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMore.setGeometry(QtCore.QRect(1130, 40, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonMore.setFont(font)
        self.pushButtonMore.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonMore.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/3 GẠCH.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonMore.setIcon(icon9)
        self.pushButtonMore.setIconSize(QtCore.QSize(50, 70))
        self.pushButtonMore.setObjectName("pushButtonMore")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(980, 170, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonExit.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/x.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon10)
        self.pushButtonExit.setIconSize(QtCore.QSize(70, 100))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.label.raise_()
        self.textEditContent.raise_()
        self.dateEditDateRate.raise_()
        self.lineEditUserName.raise_()
        self.lineEditIDRoom.raise_()
        self.pushButtonPhone.raise_()
        self.lineEditRate.raise_()
        self.label_4.raise_()
        self.pushButtonFacebook.raise_()
        self.pushButtonMail.raise_()
        self.pushButtonSendFeedback.raise_()
        self.pushButtonContact.raise_()
        self.pushButtonHome.raise_()
        self.pushButtonOrder.raise_()
        self.pushButtonPlayRoom.raise_()
        self.pushButtonPrice.raise_()
        self.pushButtonMore.raise_()
        self.pushButtonExit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1222, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEditRate.setPlaceholderText(_translate("MainWindow", "Please rate on a 5 point scale"))
