# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\ProjectKTLT\ui\HomeWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1230, 859)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 1231, 821))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/image/BACKGROUND.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButtonMail = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMail.setGeometry(QtCore.QRect(1150, 540, 71, 81))
        self.pushButtonMail.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonMail.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/MAIL.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonMail.setIcon(icon)
        self.pushButtonMail.setIconSize(QtCore.QSize(100, 60))
        self.pushButtonMail.setObjectName("pushButtonMail")
        self.pushButtonPhone = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPhone.setGeometry(QtCore.QRect(1150, 630, 71, 81))
        self.pushButtonPhone.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonPhone.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/PHONE.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPhone.setIcon(icon1)
        self.pushButtonPhone.setIconSize(QtCore.QSize(100, 60))
        self.pushButtonPhone.setObjectName("pushButtonPhone")
        self.pushButtonFacebook = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonFacebook.setGeometry(QtCore.QRect(1150, 720, 71, 81))
        self.pushButtonFacebook.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonFacebook.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/facebook-logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonFacebook.setIcon(icon2)
        self.pushButtonFacebook.setIconSize(QtCore.QSize(100, 60))
        self.pushButtonFacebook.setObjectName("pushButtonFacebook")
        self.pushButtonCatharsis = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCatharsis.setGeometry(QtCore.QRect(-10, 120, 321, 561))
        self.pushButtonCatharsis.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonCatharsis.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Catharsis.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonCatharsis.setIcon(icon3)
        self.pushButtonCatharsis.setIconSize(QtCore.QSize(600, 450))
        self.pushButtonCatharsis.setObjectName("pushButtonCatharsis")
        self.pushButtonOasis = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonOasis.setGeometry(QtCore.QRect(270, 120, 321, 561))
        self.pushButtonOasis.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonOasis.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Oasis.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonOasis.setIcon(icon4)
        self.pushButtonOasis.setIconSize(QtCore.QSize(500, 450))
        self.pushButtonOasis.setObjectName("pushButtonOasis")
        self.pushButtonGenii = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonGenii.setGeometry(QtCore.QRect(550, 120, 321, 561))
        self.pushButtonGenii.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonGenii.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Genii.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonGenii.setIcon(icon5)
        self.pushButtonGenii.setIconSize(QtCore.QSize(500, 450))
        self.pushButtonGenii.setObjectName("pushButtonGenii")
        self.pushButtonMutiny = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMutiny.setGeometry(QtCore.QRect(830, 120, 321, 561))
        self.pushButtonMutiny.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonMutiny.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Mutiny.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonMutiny.setIcon(icon6)
        self.pushButtonMutiny.setIconSize(QtCore.QSize(500, 450))
        self.pushButtonMutiny.setObjectName("pushButtonMutiny")
        self.pushButtonHome = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonHome.setGeometry(QtCore.QRect(570, 40, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonHome.setFont(font)
        self.pushButtonHome.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonHome.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/HOMEBOLD.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonHome.setIcon(icon7)
        self.pushButtonHome.setIconSize(QtCore.QSize(65, 100))
        self.pushButtonHome.setObjectName("pushButtonHome")
        self.pushButtonPlayRoom = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPlayRoom.setGeometry(QtCore.QRect(670, 40, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonPlayRoom.setFont(font)
        self.pushButtonPlayRoom.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonPlayRoom.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/PLAY ROOM.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPlayRoom.setIcon(icon8)
        self.pushButtonPlayRoom.setIconSize(QtCore.QSize(120, 100))
        self.pushButtonPlayRoom.setObjectName("pushButtonPlayRoom")
        self.pushButtonOrder = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonOrder.setGeometry(QtCore.QRect(830, 40, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonOrder.setFont(font)
        self.pushButtonOrder.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonOrder.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/ORDER.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonOrder.setIcon(icon9)
        self.pushButtonOrder.setIconSize(QtCore.QSize(75, 100))
        self.pushButtonOrder.setObjectName("pushButtonOrder")
        self.pushButtonPrice = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPrice.setGeometry(QtCore.QRect(940, 40, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonPrice.setFont(font)
        self.pushButtonPrice.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonPrice.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/PRICE.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPrice.setIcon(icon10)
        self.pushButtonPrice.setIconSize(QtCore.QSize(65, 100))
        self.pushButtonPrice.setObjectName("pushButtonPrice")
        self.pushButtonContact = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonContact.setGeometry(QtCore.QRect(1040, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonContact.setFont(font)
        self.pushButtonContact.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonContact.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/CONTACT.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonContact.setIcon(icon11)
        self.pushButtonContact.setIconSize(QtCore.QSize(95, 100))
        self.pushButtonContact.setObjectName("pushButtonContact")
        self.pushButtonMore = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMore.setGeometry(QtCore.QRect(1140, 40, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonMore.setFont(font)
        self.pushButtonMore.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonMore.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/3 GẠCH.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonMore.setIcon(icon12)
        self.pushButtonMore.setIconSize(QtCore.QSize(50, 70))
        self.pushButtonMore.setObjectName("pushButtonMore")
        self.pushButtonPanacea = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPanacea.setGeometry(QtCore.QRect(0, 0, 421, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonPanacea.setFont(font)
        self.pushButtonPanacea.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonPanacea.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/TITLE.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPanacea.setIcon(icon13)
        self.pushButtonPanacea.setIconSize(QtCore.QSize(400, 100))
        self.pushButtonPanacea.setObjectName("pushButtonPanacea")
        self.pushButtonBookNow = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBookNow.setGeometry(QtCore.QRect(380, 660, 411, 91))
        self.pushButtonBookNow.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonBookNow.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/BOOKNOW.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBookNow.setIcon(icon14)
        self.pushButtonBookNow.setIconSize(QtCore.QSize(400, 400))
        self.pushButtonBookNow.setObjectName("pushButtonBookNow")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1230, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
