# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\ProjectKTLT\ui\HomeWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1226, 861)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1221, 811))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/image/BG TRANG CHỦ.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButtonMail = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMail.setGeometry(QtCore.QRect(1130, 530, 91, 81))
        self.pushButtonMail.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonMail.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/MAIL.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonMail.setIcon(icon)
        self.pushButtonMail.setIconSize(QtCore.QSize(100, 60))
        self.pushButtonMail.setObjectName("pushButtonMail")
        self.pushButtonPhone = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPhone.setGeometry(QtCore.QRect(1130, 620, 91, 81))
        self.pushButtonPhone.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonPhone.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/PHONE.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPhone.setIcon(icon1)
        self.pushButtonPhone.setIconSize(QtCore.QSize(100, 60))
        self.pushButtonPhone.setObjectName("pushButtonPhone")
        self.pushButtonFacebook = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonFacebook.setGeometry(QtCore.QRect(1130, 710, 91, 81))
        self.pushButtonFacebook.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonFacebook.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/facebook-logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonFacebook.setIcon(icon2)
        self.pushButtonFacebook.setIconSize(QtCore.QSize(100, 60))
        self.pushButtonFacebook.setObjectName("pushButtonFacebook")
        self.pushButtonPhongChoi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPhongChoi.setGeometry(QtCore.QRect(720, 60, 121, 41))
        self.pushButtonPhongChoi.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonPhongChoi.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Phòng chơi.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPhongChoi.setIcon(icon3)
        self.pushButtonPhongChoi.setIconSize(QtCore.QSize(100, 100))
        self.pushButtonPhongChoi.setObjectName("pushButtonPhongChoi")
        self.pushButtonDatPhong = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDatPhong.setGeometry(QtCore.QRect(840, 60, 111, 41))
        self.pushButtonDatPhong.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonDatPhong.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Đặt phòng_.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonDatPhong.setIcon(icon4)
        self.pushButtonDatPhong.setIconSize(QtCore.QSize(95, 100))
        self.pushButtonDatPhong.setObjectName("pushButtonDatPhong")
        self.pushButtonBangGia = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBangGia.setGeometry(QtCore.QRect(940, 60, 111, 41))
        self.pushButtonBangGia.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonBangGia.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Bảng giá.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBangGia.setIcon(icon5)
        self.pushButtonBangGia.setIconSize(QtCore.QSize(80, 100))
        self.pushButtonBangGia.setObjectName("pushButtonBangGia")
        self.pushButtonLienHe = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLienHe.setGeometry(QtCore.QRect(1030, 60, 111, 41))
        self.pushButtonLienHe.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonLienHe.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Liên hệ.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLienHe.setIcon(icon6)
        self.pushButtonLienHe.setIconSize(QtCore.QSize(65, 100))
        self.pushButtonLienHe.setObjectName("pushButtonLienHe")
        self.pushButtonKhac = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonKhac.setGeometry(QtCore.QRect(1110, 50, 91, 61))
        self.pushButtonKhac.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonKhac.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/3 GẠCH.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonKhac.setIcon(icon7)
        self.pushButtonKhac.setIconSize(QtCore.QSize(40, 100))
        self.pushButtonKhac.setObjectName("pushButtonKhac")
        self.pushButtonCatharsis = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCatharsis.setGeometry(QtCore.QRect(0, 140, 321, 561))
        self.pushButtonCatharsis.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonCatharsis.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Catharsis.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonCatharsis.setIcon(icon8)
        self.pushButtonCatharsis.setIconSize(QtCore.QSize(600, 450))
        self.pushButtonCatharsis.setObjectName("pushButtonCatharsis")
        self.pushButtonOasis = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonOasis.setGeometry(QtCore.QRect(280, 140, 321, 561))
        self.pushButtonOasis.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonOasis.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Oasis.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonOasis.setIcon(icon9)
        self.pushButtonOasis.setIconSize(QtCore.QSize(500, 450))
        self.pushButtonOasis.setObjectName("pushButtonOasis")
        self.pushButtonGenii = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonGenii.setGeometry(QtCore.QRect(560, 140, 321, 561))
        self.pushButtonGenii.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonGenii.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Genii.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonGenii.setIcon(icon10)
        self.pushButtonGenii.setIconSize(QtCore.QSize(500, 450))
        self.pushButtonGenii.setObjectName("pushButtonGenii")
        self.pushButtonMutiny = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMutiny.setGeometry(QtCore.QRect(840, 140, 321, 561))
        self.pushButtonMutiny.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonMutiny.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Mutiny.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonMutiny.setIcon(icon11)
        self.pushButtonMutiny.setIconSize(QtCore.QSize(500, 450))
        self.pushButtonMutiny.setObjectName("pushButtonMutiny")
        self.pushButtonDatPhongNgay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDatPhongNgay.setGeometry(QtCore.QRect(310, 690, 541, 91))
        self.pushButtonDatPhongNgay.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonDatPhongNgay.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Đặt phòng ngay.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonDatPhongNgay.setIcon(icon12)
        self.pushButtonDatPhongNgay.setIconSize(QtCore.QSize(400, 200))
        self.pushButtonDatPhongNgay.setObjectName("pushButtonDatPhongNgay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1226, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
