# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\ProjectKTLT\ui\InvoiceWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 703)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1071, 651))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/image/BG Home Window.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 110, 181, 61))
        self.label_2.setStyleSheet("font-size: 22pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"color: white;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 170, 591, 381))
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 40);\n"
"border: 0.5px solid white;\n"
"border-radius: 7px;\n"
"font-size: 10pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 200, 151, 31))
        self.label_4.setStyleSheet("font-size: 13pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"color: white;\n"
"")
        self.label_4.setObjectName("label_4")
        self.lineEditInvoiceID = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditInvoiceID.setGeometry(QtCore.QRect(490, 210, 321, 21))
        self.lineEditInvoiceID.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 0.5px solid white;\n"
"border-radius: 7px;\n"
"font-size: 10pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"color: white;")
        self.lineEditInvoiceID.setObjectName("lineEditInvoiceID")
        self.lineBookingID = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineBookingID.setGeometry(QtCore.QRect(490, 250, 321, 21))
        self.lineBookingID.setStyleSheet("color: white;\n"
"background-color: rgba(255, 255, 255, 100);\n"
"border: 0.5px solid white;\n"
"border-radius: 7px;\n"
"font-size: 10pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";")
        self.lineBookingID.setObjectName("lineBookingID")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(310, 240, 151, 31))
        self.label_5.setStyleSheet("font-size: 13pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"color: white;\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(310, 280, 151, 31))
        self.label_6.setStyleSheet("font-size: 13pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"color: white;\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(310, 360, 151, 31))
        self.label_7.setStyleSheet("font-size: 13pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"color: white;\n"
"")
        self.label_7.setObjectName("label_7")
        self.linePaymentAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.linePaymentAmount.setGeometry(QtCore.QRect(490, 330, 321, 21))
        self.linePaymentAmount.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 0.5px solid white;\n"
"border-radius: 7px;\n"
"font-size: 10pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"color: white;")
        self.linePaymentAmount.setObjectName("linePaymentAmount")
        self.lineTaxAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineTaxAmount.setGeometry(QtCore.QRect(490, 370, 321, 21))
        self.lineTaxAmount.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 0.5px solid white;\n"
"border-radius: 7px;\n"
"font-size: 10pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"color: white;")
        self.lineTaxAmount.setObjectName("lineTaxAmount")
        self.lineDiscountAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineDiscountAmount.setGeometry(QtCore.QRect(490, 410, 321, 21))
        self.lineDiscountAmount.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 0.5px solid white;\n"
"border-radius: 7px;\n"
"font-size: 10pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"color: white;")
        self.lineDiscountAmount.setObjectName("lineDiscountAmount")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(310, 320, 151, 31))
        self.label_8.setStyleSheet("font-size: 13pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"color: white;\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(310, 400, 151, 31))
        self.label_9.setStyleSheet("font-size: 13pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"color: white;\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(310, 440, 151, 31))
        self.label_10.setStyleSheet("font-size: 13pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"color: white;\n"
"")
        self.label_10.setObjectName("label_10")
        self.lineTotalPayable = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineTotalPayable.setGeometry(QtCore.QRect(490, 450, 321, 21))
        self.lineTotalPayable.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 0.5px solid white;\n"
"border-radius: 7px;\n"
"font-size: 10pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"color: white;")
        self.lineTotalPayable.setObjectName("lineTotalPayable")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(310, 480, 151, 31))
        self.label_11.setStyleSheet("font-size: 13pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"color: white;\n"
"")
        self.label_11.setObjectName("label_11")
        self.comboBoxPaymentMethod = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBoxPaymentMethod.setGeometry(QtCore.QRect(490, 490, 321, 22))
        self.comboBoxPaymentMethod.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 0.5px solid white;\n"
"border-radius: 7px;\n"
"font-size: 10pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"color: white;")
        self.comboBoxPaymentMethod.setObjectName("comboBoxPaymentMethod")
        self.comboBoxPaymentMethod.addItem("")
        self.comboBoxPaymentMethod.addItem("")
        self.comboBoxPaymentMethod.addItem("")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(540, 560, 231, 81))
        self.pushButtonExit.setStyleSheet("background-color: transparent;\n"
"border: none;")
        self.pushButtonExit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon)
        self.pushButtonExit.setIconSize(QtCore.QSize(140, 140))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.pushButtonPay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPay.setGeometry(QtCore.QRect(360, 560, 221, 81))
        self.pushButtonPay.setStyleSheet("background-color: transparent;\n"
"border: none;")
        self.pushButtonPay.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Pay.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPay.setIcon(icon1)
        self.pushButtonPay.setIconSize(QtCore.QSize(140, 140))
        self.pushButtonPay.setObjectName("pushButtonPay")
        self.dateEditInvoiceDate = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEditInvoiceDate.setEnabled(True)
        self.dateEditInvoiceDate.setGeometry(QtCore.QRect(490, 290, 321, 21))
        self.dateEditInvoiceDate.setStyleSheet("background-color: rgba(255, 255, 255, 100);\n"
"border: 0.5px solid white;\n"
"border-radius: 7px;\n"
"font-size: 10pt;\n"
"font-family: \"#9Slide03 Oswald Bold\";\n"
"color: white;")
        self.dateEditInvoiceDate.setDate(QtCore.QDate(2025, 2, 14))
        self.dateEditInvoiceDate.setObjectName("dateEditInvoiceDate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1075, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "INVOICE"))
        self.label_4.setText(_translate("MainWindow", "Invoice ID:"))
        self.label_5.setText(_translate("MainWindow", "Booking ID:"))
        self.label_6.setText(_translate("MainWindow", "Invocie Date:"))
        self.label_7.setText(_translate("MainWindow", "Tax Amount:"))
        self.label_8.setText(_translate("MainWindow", "Payment Amount:"))
        self.label_9.setText(_translate("MainWindow", "Discount Amount:"))
        self.label_10.setText(_translate("MainWindow", "Total Payable:"))
        self.label_11.setText(_translate("MainWindow", "Payment Method:"))
        self.comboBoxPaymentMethod.setItemText(0, _translate("MainWindow", "Credit Card"))
        self.comboBoxPaymentMethod.setItemText(1, _translate("MainWindow", "Cash"))
        self.comboBoxPaymentMethod.setItemText(2, _translate("MainWindow", "E-wallet"))
