# Form implementation generated from reading ui file 'D:\KTLT PROJECT FINAL\ProjectKTLT\ui\LoginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1209, 857)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LoginWindowBackground = QtWidgets.QLabel(parent=self.centralwidget)
        self.LoginWindowBackground.setGeometry(QtCore.QRect(10, 0, 1201, 811))
        self.LoginWindowBackground.setText("")
        self.LoginWindowBackground.setPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/image/BG LOGIN FINAL.png"))
        self.LoginWindowBackground.setScaledContents(True)
        self.LoginWindowBackground.setWordWrap(False)
        self.LoginWindowBackground.setObjectName("LoginWindowBackground")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(560, 210, 441, 41))
        self.label.setStyleSheet("border-radius: 20px;  /* Bo góc tròn 10px */\n"
"border: 0px solid black;  /* Viền màu đen dày 2px */\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogin.setGeometry(QtCore.QRect(560, 210, 181, 41))
        self.pushButtonLogin.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonLogin.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/LOGIN BUTTON.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLogin.setIcon(icon)
        self.pushButtonLogin.setIconSize(QtCore.QSize(175, 50))
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.pushButtonEmployeeAccount = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonEmployeeAccount.setGeometry(QtCore.QRect(740, 220, 261, 21))
        self.pushButtonEmployeeAccount.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonEmployeeAccount.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/Employee account.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonEmployeeAccount.setIcon(icon1)
        self.pushButtonEmployeeAccount.setIconSize(QtCore.QSize(250, 50))
        self.pushButtonEmployeeAccount.setObjectName("pushButtonEmployeeAccount")
        self.labelUsername = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelUsername.setGeometry(QtCore.QRect(570, 290, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelUsername.setFont(font)
        self.labelUsername.setStyleSheet("color: rgb(0, 0, 127);")
        self.labelUsername.setMidLineWidth(0)
        self.labelUsername.setText("")
        self.labelUsername.setPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/User Name.jpg"))
        self.labelUsername.setObjectName("labelUsername")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditUserName.setGeometry(QtCore.QRect(570, 330, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditUserName.setFont(font)
        self.lineEditUserName.setStyleSheet("QLineEdit {\n"
"    border-radius: 15px;  /* Bo góc 15px */\n"
"    border: 2px solid gray;  /* Viền xám */\n"
"    padding: 5px;  /* Giúp chữ không bị dính vào viền */\n"
"    background-color: white;\n"
"    font-size: 16px;\n"
"}\n"
"")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.labelPassword = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelPassword.setGeometry(QtCore.QRect(570, 390, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelPassword.setFont(font)
        self.labelPassword.setStyleSheet("color: rgb(0, 0, 127);")
        self.labelPassword.setText("")
        self.labelPassword.setPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/Password.jpg"))
        self.labelPassword.setObjectName("labelPassword")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPassword.setGeometry(QtCore.QRect(570, 430, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setStyleSheet("QLineEdit {\n"
"    border-radius: 15px;  /* Bo góc 15px */\n"
"    border: 2px solid gray;  /* Viền xám */\n"
"    padding: 5px;  /* Giúp chữ không bị dính vào viền */\n"
"    background-color: white;\n"
"    font-size: 16px;\n"
"}\n"
"")
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.checkBoxSavePassword = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxSavePassword.setGeometry(QtCore.QRect(570, 480, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.checkBoxSavePassword.setFont(font)
        self.checkBoxSavePassword.setStyleSheet("color: rgb(0, 0, 127);\n"
"border-color: rgb(85, 85, 85);")
        self.checkBoxSavePassword.setObjectName("checkBoxSavePassword")
        self.pushButtonContinue = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonContinue.setGeometry(QtCore.QRect(570, 520, 421, 51))
        self.pushButtonContinue.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonContinue.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/Continue.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonContinue.setIcon(icon2)
        self.pushButtonContinue.setIconSize(QtCore.QSize(400, 50))
        self.pushButtonContinue.setObjectName("pushButtonContinue")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(570, 620, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/Don\'t have.jpg"))
        self.label_2.setObjectName("label_2")
        self.pushButtonTermsAndConditions = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonTermsAndConditions.setGeometry(QtCore.QRect(570, 660, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButtonTermsAndConditions.setFont(font)
        self.pushButtonTermsAndConditions.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    font-size: 18px;\n"
"    color: rgb(13, 169, 200);\n"
"}\n"
"")
        self.pushButtonTermsAndConditions.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/Terms and Conditions.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonTermsAndConditions.setIcon(icon3)
        self.pushButtonTermsAndConditions.setIconSize(QtCore.QSize(300, 200))
        self.pushButtonTermsAndConditions.setObjectName("pushButtonTermsAndConditions")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(780, 660, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/and.jpg"))
        self.label_4.setObjectName("label_4")
        self.pushButtonSignUp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSignUp.setGeometry(QtCore.QRect(810, 620, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButtonSignUp.setFont(font)
        self.pushButtonSignUp.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    font-size: 18px;\n"
"    color: rgb(13, 169, 200);\n"
"}\n"
"")
        self.pushButtonSignUp.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/Sign Up.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSignUp.setIcon(icon4)
        self.pushButtonSignUp.setIconSize(QtCore.QSize(200, 200))
        self.pushButtonSignUp.setObjectName("pushButtonSignUp")
        self.pushButtonIForgotMyPassword = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonIForgotMyPassword.setGeometry(QtCore.QRect(560, 580, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButtonIForgotMyPassword.setFont(font)
        self.pushButtonIForgotMyPassword.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    font-size: 18px;\n"
"    color: rgb(13, 169, 200);\n"
"}\n"
"")
        self.pushButtonIForgotMyPassword.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/I forgot my password.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonIForgotMyPassword.setIcon(icon5)
        self.pushButtonIForgotMyPassword.setIconSize(QtCore.QSize(400, 100))
        self.pushButtonIForgotMyPassword.setObjectName("pushButtonIForgotMyPassword")
        self.pushButtonMail = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMail.setGeometry(QtCore.QRect(1130, 560, 61, 51))
        self.pushButtonMail.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonMail.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/MAIL.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonMail.setIcon(icon6)
        self.pushButtonMail.setIconSize(QtCore.QSize(400, 50))
        self.pushButtonMail.setObjectName("pushButtonMail")
        self.pushButtonPhone = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPhone.setGeometry(QtCore.QRect(1130, 640, 61, 51))
        self.pushButtonPhone.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonPhone.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/PHONE.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPhone.setIcon(icon7)
        self.pushButtonPhone.setIconSize(QtCore.QSize(400, 50))
        self.pushButtonPhone.setObjectName("pushButtonPhone")
        self.pushButtonFacebook = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonFacebook.setGeometry(QtCore.QRect(1130, 720, 61, 51))
        self.pushButtonFacebook.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    color: white;  /* Màu chữ */\n"
"    font-size: 18px;\n"
"}\n"
"")
        self.pushButtonFacebook.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/facebook-logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonFacebook.setIcon(icon8)
        self.pushButtonFacebook.setIconSize(QtCore.QSize(400, 50))
        self.pushButtonFacebook.setObjectName("pushButtonFacebook")
        self.pushButtonTermsAndConditions_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonTermsAndConditions_2.setGeometry(QtCore.QRect(810, 650, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButtonTermsAndConditions_2.setFont(font)
        self.pushButtonTermsAndConditions_2.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0); /* Nền trong suốt */\n"
"    border: none;  /* Loại bỏ viền */\n"
"    font-size: 18px;\n"
"    color: rgb(13, 169, 200);\n"
"}\n"
"")
        self.pushButtonTermsAndConditions_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("D:\\KTLT PROJECT FINAL\\ProjectKTLT\\ui\\../assets/icons/Privacy Login.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonTermsAndConditions_2.setIcon(icon9)
        self.pushButtonTermsAndConditions_2.setIconSize(QtCore.QSize(300, 300))
        self.pushButtonTermsAndConditions_2.setObjectName("pushButtonTermsAndConditions_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1209, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBoxSavePassword.setText(_translate("MainWindow", "Save password"))
