# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\ProjectKTLT\ui\LoginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1193, 834)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(11, 11, 1171, 761))
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/image/LoginWIndow.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditUserName.setGeometry(QtCore.QRect(570, 350, 301, 31))
        font = QtGui.QFont()
        font.setItalic(True)
        self.lineEditUserName.setFont(font)
        self.lineEditUserName.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #3498db; /* Màu viền */\n"
"    border-radius: 10px;      /* Độ bo góc */\n"
"    padding: 5px;            /* Khoảng cách giữa chữ và viền */\n"
"    background-color: #ffffff; /* Màu nền */\n"
"    color: #000000;          /* Màu chữ */\n"
"}\n"
"")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.lineEditPassWord = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPassWord.setGeometry(QtCore.QRect(570, 450, 301, 31))
        font = QtGui.QFont()
        font.setItalic(True)
        self.lineEditPassWord.setFont(font)
        self.lineEditPassWord.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #3498db; /* Màu viền */\n"
"    border-radius: 10px;      /* Độ bo góc */\n"
"    padding: 5px;            /* Khoảng cách giữa chữ và viền */\n"
"    background-color: #ffffff; /* Màu nền */\n"
"    color: #000000;          /* Màu chữ */\n"
"}\n"
"")
        self.lineEditPassWord.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassWord.setObjectName("lineEditPassWord")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogin.setGeometry(QtCore.QRect(570, 530, 301, 31))
        self.pushButtonLogin.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButtonLogin.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButtonLogin.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonLogin.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Làm nền trong suốt */\n"
"    border: none;                 /* Loại bỏ viền */\n"
"    color: #000000;               /* Màu chữ (nếu có chữ) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 0.1); /* Hiệu ứng hover nhẹ */\n"
"}\n"
"")
        self.pushButtonLogin.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Continue.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLogin.setIcon(icon)
        self.pushButtonLogin.setIconSize(QtCore.QSize(300, 301))
        self.pushButtonLogin.setAutoRepeatDelay(100)
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.checkBoxSavePassword = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxSavePassword.setGeometry(QtCore.QRect(580, 490, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxSavePassword.setFont(font)
        self.checkBoxSavePassword.setChecked(True)
        self.checkBoxSavePassword.setObjectName("checkBoxSavePassword")
        self.pushButtonForgotPassword = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonForgotPassword.setGeometry(QtCore.QRect(570, 590, 171, 31))
        self.pushButtonForgotPassword.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Làm nền trong suốt */\n"
"    border: none;                 /* Loại bỏ viền */\n"
"    color: #000000;               /* Màu chữ (nếu có chữ) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 0.1); /* Hiệu ứng hover nhẹ */\n"
"}\n"
"")
        self.pushButtonForgotPassword.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/I forgot my password.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonForgotPassword.setIcon(icon1)
        self.pushButtonForgotPassword.setIconSize(QtCore.QSize(150, 100))
        self.pushButtonForgotPassword.setObjectName("pushButtonForgotPassword")
        self.pushButtonSignUp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSignUp.setGeometry(QtCore.QRect(750, 630, 61, 20))
        self.pushButtonSignUp.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Làm nền trong suốt */\n"
"    border: none;                 /* Loại bỏ viền */\n"
"    color: #000000;               /* Màu chữ (nếu có chữ) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 0.1); /* Hiệu ứng hover nhẹ */\n"
"}\n"
"")
        self.pushButtonSignUp.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Sign Up.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSignUp.setIcon(icon2)
        self.pushButtonSignUp.setIconSize(QtCore.QSize(50, 100))
        self.pushButtonSignUp.setObjectName("pushButtonSignUp")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1193, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEditUserName.setPlaceholderText(_translate("MainWindow", "Enter your username"))
        self.lineEditPassWord.setPlaceholderText(_translate("MainWindow", "Enter your password"))
        self.checkBoxSavePassword.setText(_translate("MainWindow", "Keep Me Logged In"))
