# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\ProjectKTLT\ui\OnlinePaymentWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 861)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-6, -5, 1231, 821))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/image/ONLINE PAYMENT.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButtonMail = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMail.setGeometry(QtCore.QRect(1120, 500, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonMail.setFont(font)
        self.pushButtonMail.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonMail.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/MAIL.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonMail.setIcon(icon)
        self.pushButtonMail.setIconSize(QtCore.QSize(70, 100))
        self.pushButtonMail.setObjectName("pushButtonMail")
        self.pushButtonPhone = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPhone.setGeometry(QtCore.QRect(1110, 600, 101, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonPhone.setFont(font)
        self.pushButtonPhone.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonPhone.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/PHONE.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPhone.setIcon(icon1)
        self.pushButtonPhone.setIconSize(QtCore.QSize(100, 70))
        self.pushButtonPhone.setObjectName("pushButtonPhone")
        self.pushButtonFacebook = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonFacebook.setGeometry(QtCore.QRect(1120, 700, 81, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonFacebook.setFont(font)
        self.pushButtonFacebook.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonFacebook.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/facebook-logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonFacebook.setIcon(icon2)
        self.pushButtonFacebook.setIconSize(QtCore.QSize(70, 80))
        self.pushButtonFacebook.setObjectName("pushButtonFacebook")
        self.lineEditAccountNumber = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditAccountNumber.setGeometry(QtCore.QRect(490, 450, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditAccountNumber.setFont(font)
        self.lineEditAccountNumber.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Màu nền trắng */\n"
"    color: #2c3e50; /* Màu chữ xanh đậm */\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px;\n"
"    font-size: 25px;\n"
"    border-color: rgb(0, 0, 0);\n"
"    font-weight: bold;\n"
"}")
        self.lineEditAccountNumber.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditAccountNumber.setObjectName("lineEditAccountNumber")
        self.lineEditBeneficiaryBank = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditBeneficiaryBank.setGeometry(QtCore.QRect(490, 540, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditBeneficiaryBank.setFont(font)
        self.lineEditBeneficiaryBank.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Màu nền trắng */\n"
"    color: #2c3e50; /* Màu chữ xanh đậm */\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px;\n"
"    font-size: 25px;\n"
"    font-weight:bold;\n"
"}")
        self.lineEditBeneficiaryBank.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditBeneficiaryBank.setObjectName("lineEditBeneficiaryBank")
        self.lineEditBeneficiaryName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditBeneficiaryName.setGeometry(QtCore.QRect(490, 630, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditBeneficiaryName.setFont(font)
        self.lineEditBeneficiaryName.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Màu nền trắng */\n"
"    color: #2c3e50; /* Màu chữ xanh đậm */\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px;\n"
"    font-size: 25px;\n"
"    font-weight:bold;\n"
"}")
        self.lineEditBeneficiaryName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditBeneficiaryName.setObjectName("lineEditBeneficiaryName")
        self.pushButtonConfirmPayment = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonConfirmPayment.setGeometry(QtCore.QRect(440, 730, 391, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonConfirmPayment.setFont(font)
        self.pushButtonConfirmPayment.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonConfirmPayment.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/Confirm Payment.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonConfirmPayment.setIcon(icon3)
        self.pushButtonConfirmPayment.setIconSize(QtCore.QSize(350, 300))
        self.pushButtonConfirmPayment.setObjectName("pushButtonConfirmPayment")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(970, 170, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonExit.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/x.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon4)
        self.pushButtonExit.setIconSize(QtCore.QSize(70, 100))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 230, 191, 191))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/image/QR CODE.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(730, 230, 91, 51))
        font = QtGui.QFont()
        font.setFamily("VNI-Swiss-Condense")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel, QPushButton, QRadioButton {\n"
"    font-family: \"VNI-Swiss-Condense\"; /* Chọn font cố định */\n"
"    font-size: 35px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_3.setObjectName("label_3")
        self.lineEditTotal = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditTotal.setGeometry(QtCore.QRect(740, 310, 221, 41))
        self.lineEditTotal.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Màu nền trắng */\n"
"    color: #2c3e50; /* Màu chữ xanh đậm */\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px;\n"
"    font-size: 25px;\n"
"    font-weight:bold;\n"
"}")
        self.lineEditTotal.setObjectName("lineEditTotal")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1220, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEditAccountNumber.setText(_translate("MainWindow", "0385087129"))
        self.lineEditBeneficiaryBank.setText(_translate("MainWindow", "MB BANK"))
        self.lineEditBeneficiaryName.setText(_translate("MainWindow", "PHAN HONG NGOC"))
        self.label_3.setText(_translate("MainWindow", "Total"))
