# Form implementation generated from reading ui file 'C:\Users\ADMIN\PycharmProjects\ProjectKTLT\ui\PopUpRoomWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1227, 860)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 280, 55, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-6, -5, 1241, 821))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/image/ROOM DETAIL.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButtonHome = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonHome.setGeometry(QtCore.QRect(610, 40, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonHome.setFont(font)
        self.pushButtonHome.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonHome.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/HOME.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonHome.setIcon(icon)
        self.pushButtonHome.setIconSize(QtCore.QSize(65, 100))
        self.pushButtonHome.setObjectName("pushButtonHome")
        self.pushButtonPlayRoom = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPlayRoom.setGeometry(QtCore.QRect(700, 40, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonPlayRoom.setFont(font)
        self.pushButtonPlayRoom.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonPlayRoom.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/PLAY ROOM.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPlayRoom.setIcon(icon1)
        self.pushButtonPlayRoom.setIconSize(QtCore.QSize(120, 100))
        self.pushButtonPlayRoom.setObjectName("pushButtonPlayRoom")
        self.pushButtonOrder = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonOrder.setGeometry(QtCore.QRect(850, 40, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonOrder.setFont(font)
        self.pushButtonOrder.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonOrder.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/ORDER.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonOrder.setIcon(icon2)
        self.pushButtonOrder.setIconSize(QtCore.QSize(75, 100))
        self.pushButtonOrder.setObjectName("pushButtonOrder")
        self.pushButtonPrice = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPrice.setGeometry(QtCore.QRect(950, 40, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonPrice.setFont(font)
        self.pushButtonPrice.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonPrice.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/PRICE.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPrice.setIcon(icon3)
        self.pushButtonPrice.setIconSize(QtCore.QSize(65, 100))
        self.pushButtonPrice.setObjectName("pushButtonPrice")
        self.pushButtonContact = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonContact.setGeometry(QtCore.QRect(1040, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonContact.setFont(font)
        self.pushButtonContact.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonContact.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/CONTACT.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonContact.setIcon(icon4)
        self.pushButtonContact.setIconSize(QtCore.QSize(95, 100))
        self.pushButtonContact.setObjectName("pushButtonContact")
        self.pushButtonMore = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMore.setGeometry(QtCore.QRect(1140, 40, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonMore.setFont(font)
        self.pushButtonMore.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonMore.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/3 GẠCH.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonMore.setIcon(icon5)
        self.pushButtonMore.setIconSize(QtCore.QSize(50, 70))
        self.pushButtonMore.setObjectName("pushButtonMore")
        self.pushButtonMail = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMail.setGeometry(QtCore.QRect(1120, 500, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonMail.setFont(font)
        self.pushButtonMail.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonMail.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/MAIL.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonMail.setIcon(icon6)
        self.pushButtonMail.setIconSize(QtCore.QSize(70, 100))
        self.pushButtonMail.setObjectName("pushButtonMail")
        self.pushButtonPhone = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPhone.setGeometry(QtCore.QRect(1110, 600, 101, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonPhone.setFont(font)
        self.pushButtonPhone.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonPhone.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/PHONE.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPhone.setIcon(icon7)
        self.pushButtonPhone.setIconSize(QtCore.QSize(100, 70))
        self.pushButtonPhone.setObjectName("pushButtonPhone")
        self.pushButtonFacebook = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonFacebook.setGeometry(QtCore.QRect(1120, 710, 81, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonFacebook.setFont(font)
        self.pushButtonFacebook.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonFacebook.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/facebook-logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonFacebook.setIcon(icon8)
        self.pushButtonFacebook.setIconSize(QtCore.QSize(70, 80))
        self.pushButtonFacebook.setObjectName("pushButtonFacebook")
        self.lineEditRoomID = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditRoomID.setGeometry(QtCore.QRect(440, 250, 511, 41))
        self.lineEditRoomID.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Màu nền trắng */\n"
"    color: #2c3e50; /* Màu chữ xanh đậm */\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px;\n"
"    font-size: 25px;\n"
"    font-weight:bold;\n"
"}")
        self.lineEditRoomID.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditRoomID.setObjectName("lineEditRoomID")
        self.lineEditRoomName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditRoomName.setGeometry(QtCore.QRect(440, 320, 511, 41))
        self.lineEditRoomName.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Màu nền trắng */\n"
"    color: #2c3e50; /* Màu chữ xanh đậm */\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px;\n"
"    font-size: 25px;\n"
"    font-weight:bold;\n"
"}")
        self.lineEditRoomName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditRoomName.setObjectName("lineEditRoomName")
        self.lineEditQuantity = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditQuantity.setGeometry(QtCore.QRect(440, 400, 511, 41))
        self.lineEditQuantity.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Màu nền trắng */\n"
"    color: #2c3e50; /* Màu chữ xanh đậm */\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px;\n"
"    font-size: 25px;\n"
"    font-weight:bold;\n"
"}")
        self.lineEditQuantity.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditQuantity.setObjectName("lineEditQuantity")
        self.lineEditUserPrice = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditUserPrice.setGeometry(QtCore.QRect(440, 480, 511, 41))
        self.lineEditUserPrice.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Màu nền trắng */\n"
"    color: #2c3e50; /* Màu chữ xanh đậm */\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px;\n"
"    font-size: 25px;\n"
"    font-weight:bold;\n"
"}")
        self.lineEditUserPrice.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditUserPrice.setObjectName("lineEditUserPrice")
        self.lineEditUserStatus = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditUserStatus.setGeometry(QtCore.QRect(440, 560, 511, 41))
        self.lineEditUserStatus.setStyleSheet("QLineEdit {\n"
"    background-color: white; /* Màu nền trắng */\n"
"    color: #2c3e50; /* Màu chữ xanh đậm */\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 5px;\n"
"    font-size: 25px;\n"
"    font-weight:bold;\n"
"}")
        self.lineEditUserStatus.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditUserStatus.setObjectName("lineEditUserStatus")
        self.textEditDescription = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEditDescription.setGeometry(QtCore.QRect(440, 630, 511, 121))
        self.textEditDescription.setStyleSheet("QTextEdit {\n"
"    background-color: white;\n"
"    color: black;\n"
"    font-size: 16px;\n"
"    border: 2px solid #3498db; /* Viền xanh */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 8px;\n"
"}")
        self.textEditDescription.setObjectName("textEditDescription")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(980, 160, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: white;  /* Màu chữ */\n"
"}")
        self.pushButtonExit.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("C:\\Users\\ADMIN\\PycharmProjects\\ProjectKTLT\\ui\\../assets/icons/x.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon9)
        self.pushButtonExit.setIconSize(QtCore.QSize(70, 100))
        self.pushButtonExit.setObjectName("pushButtonExit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1227, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
